version: '3'

services:
  mosquitto:
    restart: always
    image: eclipse-mosquitto:latest
    container_name: broker1
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - ./node-red:/data

  influxdb:
    restart: always
    image: influxdb:1.8.6
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "iot_db"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
    volumes:
      - tig-data:/var/lib/influxdb
    networks:
      - tig-net

  grafana:
    image: grafana/grafana:7.5.9
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - tig-data:/var/lib/grafana
    restart: always
    networks:
      - tig-net

  telegraf:
    restart: always
    image: telegraf:1.19.0
    depends_on:
      - influxdb
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      DATABASE: "iot_db"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    tty: true
    networks:
      - tig-net
    privileged: true

volumes:
  tig-data:

networks:
  tig-net:
    driver: bridge
